name: firebasedemo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  get: ^4.6.3
  get_it: ^7.1.3
  line_awesome_flutter: ^2.0.0
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  fluttertoast: ^8.0.9
  cloud_firestore: ^4.13.2
  shared_preferences: ^2.0.15
  firebase_storage: ^11.5.2
  flutter_easyloading: ^3.0.5
  flutter_staggered_animations: ^1.1.1
  google_sign_in: ^5.4.3
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Head
      fonts:
        - asset: assets/fonts/FONT_HEAD.ttf
    - family: Normal
      fonts:
        - asset: assets/fonts/FONT_NORMAL.ttf
    - family: Subtitle
      fonts:
        - asset: assets/fonts/FONT_SUBTITLE.ttf
    - family: Title
      fonts:
        - asset: assets/fonts/FONT_TITLE.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
    - family: NewsCycle
      fonts:
        - asset: assets/fonts/ClanNarrow_News.ttf
    - family: SfPro
      fonts:
        - asset: assets/fonts/SFPRO_DISPLAY_REGULAR.ttf
    - family: SfProText
      fonts:
        - asset: assets/fonts/SF_Pro_Text.otf
    - family: ClanNarrowMedium
      fonts:
        - asset: assets/fonts/FF_Clan_OT_Narrow_Medium.otf
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
